### ISSUE TITLE
Sadly its not possible to build

### ISSUE THREAD

**Issue by pySilver** [ICEBERG98/Go-Consul-Cleanup#1]
Readme contains invalid instructions I guess. This package cannot be build (naming collisions and missing libs).

**Comment by Kashish-Soni** [comment]
I'll just look into this, add a refactor

**Comment by ICEBERG98** [comment]
Hey @pySilver , I have fixed the problem, this now build succesfully.
Had to abandon the project earlier, since I was facing a job crisis.

Cheers!

**Comment by pySilver** [comment]
Thank you!
